---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportQuery
metadata:
  labels:
    subscription-watch: "true"
  name: sw-core-usage-product-components-lookback
spec:
  view:
    disabled: true
  columns:
    - name: pod
      type: varchar
      unit: kubernetes_pod
    - name: project
      type: varchar
      unit: kubernetes_namespace
    - name: company
      type: varchar
    - name: product
      type: varchar
    - name: component
      type: varchar
    - name: component_type
      type: varchar
    - name: used_cores
      type: double
    - name: interval_start
      type: timestamp
      unit: date
  inputs:
    - name: ReportingStart
      type: time
    - default: sw-core-usage-product-components
      name: SubscriptionWatchProductUsageReportName
      type: Report
  query: |
    SELECT
      pod,
      project,
      company,
      product,
      component,
      component_type,
      used_cores,
      interval_start
    FROM {| .Report.Inputs.SubscriptionWatchProductUsageReportName | reportTableName |}
    WHERE {| .Report.Inputs.SubscriptionWatchProductUsageReportName | reportTableName |}.interval_start >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}' - interval '3' day
    ORDER BY interval_start, company, product, component_type, project
