---

apiVersion: subscription-watch.openshift.io/v1alpha1
kind: SubscriptionWatch
metadata:
  name: subs-watch-setup
spec:
  clusterID: 'cluster-id-placeholder'
  reporting_operator_token_name: 'reporting-operator-token-placeholder'
  validate_cert: 'false'
  authentication: 'basic'
  authentication_secret_name: 'auth-secret-name-placeholder'
  ingress_url: 'http://localhost:8000'
  upload_wait: 1
